function(local_ip platform)
    if(${CMAKE_SYSTEM_NAME} STREQUAL "Windows")
        message("Loading local ipv4 for ${CMAKE_SYSTEM_NAME}")
        return(0)
    elseif(${CMAKE_SYSTEM_NAME} STREQUAL "Darwin")
    return(0)
    elseif(${CMAKE_SYSTEM_NAME} STREQUAL "Linux")
    return(0)
    else()
        message("Failed to detect platorm")
        return("null")
    endif()
endfunction()
